[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/payments"
  to = "/.netlify/functions/payments"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "20"

[context.deploy-preview.environment]
  NODE_VERSION = "20"

[context.branch-deploy.environment]
  NODE_VERSION = "20"