[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "#vite"

[context.production.environment]
  NODE_VERSION = "20"
  VITE_JSONBIN_MASTER_KEY = "$2a$10$obpnm2NOc8Wcx60hS6ZWJ.xw4OP4uhkVdcKHWu06FZxjKyIQuUUUu"
  VITE_USERS_BIN_ID = "68d8d48a43b1c97be95294d4"
  VITE_DATES_BIN_ID = "68d8d49f43b1c97be95294e1"
  VITE_MESSAGES_BIN_ID = "68d8d468ae596e708ffe4f2b"
  VITE_PAYMENTS_BIN_ID = "68d8d4bdd0ea881f408d861f"
  PAYPAL_CLIENT_ID = "YOUR_PAYPAL_PRODUCTION_CLIENT_ID"
  PAYPAL_CLIENT_SECRET = "YOUR_PAYPAL_PRODUCTION_SECRET"
  CORS_ORIGIN = "*"

[context.deploy-preview.environment]
  NODE_VERSION = "20"
  VITE_JSONBIN_MASTER_KEY = "$2a$10$obpnm2NOc8Wcx60hS6ZWJ.xw4OP4uhkVdcKHWu06FZxjKyIQuUUUu"
  VITE_USERS_BIN_ID = "68d8d48a43b1c97be95294d4"
  VITE_DATES_BIN_ID = "68d8d49f43b1c97be95294e1"
  VITE_MESSAGES_BIN_ID = "68d8d468ae596e708ffe4f2b"
  VITE_PAYMENTS_BIN_ID = "68d8d4bdd0ea881f408d861f"

[context.branch-deploy.environment]
  NODE_VERSION = "20"
  VITE_JSONBIN_MASTER_KEY = "$2a$10$obpnm2NOc8Wcx60hS6ZWJ.xw4OP4uhkVdcKHWu06FZxjKyIQuUUUu"
  VITE_USERS_BIN_ID = "68d8d48a43b1c97be95294d4"
  VITE_DATES_BIN_ID = "68d8d49f43b1c97be95294e1"
  VITE_MESSAGES_BIN_ID = "68d8d468ae596e708ffe4f2b"
  VITE_PAYMENTS_BIN_ID = "68d8d4bdd0ea881f408d861f"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200