[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# DISABLE NEON EXTENSIONS - USE SUPABASE ONLY
[dev]
  framework = "#vite"

# NO NEON - SUPABASE ONLY
[context.production.environment]
  NODE_VERSION = "20"
  DATABASE_PROVIDER = "supabase"
  SUPABASE_URL = "https://xclhndjglcnkcvibqqgv.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbGhuZGpnbGNua2N2aWJxcWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzOTM2MDEsImV4cCI6MjA0OTk2OTYwMX0.b3D6KBTsQyM6pvZDhN0wkjH3eKaYWBOPFcqNAA0mOLI"
  SEED_ENABLED = "true"
  SEED_TOKEN = "FORCE_SEED_NOW_123"

[context.deploy-preview.environment]
  NODE_VERSION = "20"
  DATABASE_PROVIDER = "supabase"
  SUPABASE_URL = "https://xclhndjglcnkcvibqqgv.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbGhuZGpnbGNua2N2aWJxcWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzOTM2MDEsImV4cCI6MjA0OTk2OTYwMX0.b3D6KBTsQyM6pvZDhN0wkjH3eKaYWBOPFcqNAA0mOLI"

[context.branch-deploy.environment]
  NODE_VERSION = "20"
  DATABASE_PROVIDER = "supabase"
  SUPABASE_URL = "https://xclhndjglcnkcvibqqgv.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbGhuZGpnbGNua2N2aWJxcWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzOTM2MDEsImV4cCI6MjA0OTk2OTYwMX0.b3D6KBTsQyM6pvZDhN0wkjH3eKaYWBOPFcqNAA0mOLI"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200