[build]
  publish = "dist"
  command = "npm run build"
  runtime = "nodejs20.x"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "#vite"

[context.production.environment]
  NODE_VERSION = "20"
  NEON_DATABASE_URL = "YOUR_NEON_DATABASE_URL_HERE"
  PAYPAL_CLIENT_ID = "YOUR_PAYPAL_PRODUCTION_CLIENT_ID"
  PAYPAL_CLIENT_SECRET = "YOUR_PAYPAL_PRODUCTION_SECRET"
  GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"
  CORS_ORIGIN = "YOUR_PRODUCTION_DOMAIN_HERE"

[context.deploy-preview.environment]
  NODE_VERSION = "20"
  NEON_DATABASE_URL = "YOUR_NEON_DATABASE_URL_HERE"
  GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"

[context.branch-deploy.environment]
  NODE_VERSION = "20"
  NEON_DATABASE_URL = "YOUR_NEON_DATABASE_URL_HERE"
  GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200