[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# DISABLE NEON EXTENSIONS - USE SUPABASE ONLY
[dev]
  framework = "#vite"

# NO NEON - SUPABASE ONLY
[context.production.environment]
  NODE_VERSION = "20"
  DATABASE_PROVIDER = "supabase"

[context.deploy-preview.environment]
  NODE_VERSION = "20"
  DATABASE_PROVIDER = "supabase"

[context.branch-deploy.environment]
  NODE_VERSION = "20"
  DATABASE_PROVIDER = "supabase"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200